### ISSUE TITLE
Review Comments

### ISSUE THREAD

**Issue by raghuprathap** [hellopramith/capsule-project-development#1]
`Chai` is being imported but never added as a dependency to the project so throwing below error while running test cases.
![image](https://user-images.githubusercontent.com/3498847/45279001-19ecd380-b4ed-11e8-8b6c-c2117e01d82d.png)

**Comment by raghuprathap** [comment]
Sorry choose wrong repo. Please ignore the comment above. Hence closing.

**Comment by pramithprakash** [comment]
Hi @raghuprathap , Chai added to dependencies. Thanks
please fetch again

**Comment by pramithprakash** [comment]
Hi @raghuprathap  ,  New room creation functionality added
