### ISSUE TITLE
CI/CD implementation pending

### ISSUE THREAD

**Issue by raghuprathap** [hellopramith/capsule-project-development#3]

**Comment by pramithprakash** [comment]
Implemented herokuapp &CircleCI
https://capsule-project-development.herokuapp.com/

<img width="1423" alt="screen shot 2018-09-10 at 4 21 50 pm" src="https://user-images.githubusercontent.com/8134489/45293401-ba56ee00-b515-11e8-98e3-f77015b70f3e.png">

**Comment by pramithprakash** [comment]
<img width="1406" alt="screen shot 2018-09-10 at 4 29 07 pm" src="https://user-images.githubusercontent.com/8134489/45293763-b5466e80-b516-11e8-8063-d7b275d9a37d.png">
Its working :

**Comment by raghuprathap** [comment]
Seems build failing also there should be in a single workflow 2 jobs should be there. I see only build job but no deploy job.
![image](https://user-images.githubusercontent.com/3498847/45403565-bee7e780-b678-11e8-9be6-d91de0e49127.png)

**Comment by pramithprakash** [comment]
Corrected, now build is successful, working on deploy job
<img width="1431" alt="screen shot 2018-09-12 at 11 53 32 am" src="https://user-images.githubusercontent.com/8134489/45405979-8220ee00-b682-11e8-8b87-afe8338f46d5.png">

**Comment by pramithprakash** [comment]
<img width="1439" alt="screen shot 2018-09-12 at 12 14 43 pm" src="https://user-images.githubusercontent.com/8134489/45406895-7551c980-b685-11e8-8cda-a32237991c39.png">
Both build & deploy added and success. Thanks
