### ISSUE TITLE
Review Comments on Deployed App.

### ISSUE THREAD

**Issue by Fawke** [hellopramith/capsule-project-development#4]
1. The chat screen is not loading. 
![screenshot from 2018-09-13 11-01-35](https://user-images.githubusercontent.com/14229985/45468859-8a416200-b744-11e8-8fa7-84bbd27d29d5.png)

2. On hittig page refresh, it's redirecting me back to the `Enter username` page. It should stay on the chatscreen page.

3. Please write more unit test cases for all of your React components and for all the Reducers that you've wrtitten.

**Comment by pramithprakash** [comment]
Hi @Fawke ,
Its deployed in heroku, please check here.
https://capsule-project-development.herokuapp.com/

Its loading fine

**Comment by pramithprakash** [comment]
Hi @Fawke ,
On page refreshing issue fixed. and is working fine as expected.
https://capsule-project-development.herokuapp.com/

Thanks

**Comment by Fawke** [comment]
1. Messages are not updating instantaneously, the previous message is getting rendered when I send the next message. [BUG]

**Comment by pramithprakash** [comment]
@Fawke , I have fixed this issue. Thanks
